# Generated by Django 4.2.30 on 2026-07-16 18:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import leads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=180, verbose_name='Business / league name')),
                ('contact_person', models.CharField(blank=True, db_index=True, max_length=140)),
                ('category', models.CharField(choices=[('cricket_league', 'Cricket League'), ('cricket_team', 'Cricket Team'), ('cricket_club', 'Cricket Club'), ('cricket_academy', 'Cricket Academy'), ('event_company', 'Event Company'), ('sports_media', 'Sports Media'), ('streaming_partner', 'Live Streaming Partner'), ('cafe', 'Cafe'), ('travel_business', 'Travel Business'), ('real_estate', 'Real Estate'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, default='India', max_length=120)),
                ('instagram_handle', models.CharField(blank=True, db_index=True, max_length=120)),
                ('instagram_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=40)),
                ('website_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('offline', 'Offline'), ('other', 'Other')], db_index=True, default='instagram', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('dm_sent', 'DM Sent'), ('email_sent', 'Email Sent'), ('replied', 'Replied'), ('demo_requested', 'Demo Requested'), ('demo_sent', 'Demo Sent'), ('waiting', 'Waiting'), ('follow_up_due', 'Follow-up Due'), ('follow_up_1', 'Follow-up 1'), ('follow_up_2', 'Follow-up 2'), ('meeting_scheduled', 'Meeting Scheduled'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('not_interested', 'Not Interested')], db_index=True, default='new', max_length=30)),
                ('first_contact_date', models.DateField(blank=True, null=True)),
                ('last_contact_date', models.DateField(blank=True, db_index=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, db_index=True, null=True)),
                ('expected_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposal_sent', models.BooleanField(db_index=True, default=False)),
                ('demo_sent', models.BooleanField(db_index=True, default=False)),
                ('reply_received', models.BooleanField(db_index=True, default=False)),
                ('meeting_scheduled', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to=leads.models.lead_attachment_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp', 'mp4', 'mov', 'doc', 'docx', 'xls', 'xlsx']), leads.models.validate_attachment_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.lead')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Lead Created'), ('note', 'Note Added'), ('dm_sent', 'Instagram DM Sent'), ('email_sent', 'Email Sent'), ('whatsapp_sent', 'WhatsApp Message Sent'), ('replied', 'Reply Received'), ('demo_requested', 'Demo Requested'), ('demo_sent', 'Demo Sent'), ('follow_up_sent', 'Follow-up Sent'), ('call', 'Call Completed'), ('meeting', 'Meeting Scheduled'), ('proposal', 'Proposal Sent'), ('status_changed', 'Status Changed'), ('won', 'Lead Won'), ('lost', 'Lead Lost'), ('other', 'Other')], db_index=True, default='note', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('activity_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'lead activities',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', 'status', 'next_follow_up_date'], name='leads_lead_is_arch_72b812_idx'),
        ),
    ]
