# Generated by Django 4.2.30 on 2026-07-06 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_SERVICE_CATEGORIES = [
    ("Restaurant Websites", "restaurant-websites"),
    ("Cafe Websites", "cafe-websites"),
    ("Hotel Websites", "hotel-websites"),
    ("Travel Agency Websites", "travel-agency-websites"),
    ("Salon & Makeup Artist Websites", "salon-makeup-artist-websites"),
    ("Wedding & Event Planner Websites", "wedding-event-planner-websites"),
    ("Pet Shop Websites", "pet-shop-websites"),
    ("Gym Websites", "gym-websites"),
    ("Real Estate Websites", "real-estate-websites"),
    ("Portfolio Websites", "portfolio-websites"),
    ("Business Websites", "business-websites"),
    ("Ecommerce / Product Catalogue Websites", "ecommerce-product-catalogue-websites"),
    ("Other", "other"),
]


def create_default_service_categories(apps, schema_editor):
    ServiceCategory = apps.get_model("core", "ServiceCategory")
    for name, slug in DEFAULT_SERVICE_CATEGORIES:
        ServiceCategory.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "description": f"CRM category for {name.lower()}.",
                "is_active": True,
            },
        )


def remove_default_service_categories(apps, schema_editor):
    # Keep rollback non-destructive if client records have already been attached.
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_update_wedding_event_demo_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('contact_person', models.CharField(max_length=140)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business_type', models.CharField(blank=True, max_length=140)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('google_maps_link', models.URLField(blank=True)),
                ('current_website', models.URLField(blank=True)),
                ('business_logo', models.FileField(blank=True, upload_to='client_logos/')),
                ('lead_source', models.CharField(choices=[('Google Maps', 'Google Maps'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp'), ('LinkedIn', 'LinkedIn'), ('Referral', 'Referral'), ('Offline', 'Offline'), ('Website Form', 'Website Form'), ('Other', 'Other')], default='Other', max_length=40)),
                ('communication_channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Instagram', 'Instagram'), ('Call', 'Call'), ('Email', 'Email'), ('LinkedIn', 'LinkedIn'), ('Offline', 'Offline'), ('Other', 'Other')], default='WhatsApp', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, max_length=140)),
                ('package_selected', models.CharField(blank=True, max_length=180)),
                ('final_scope_summary', models.TextField(blank=True)),
                ('pages_required', models.TextField(blank=True)),
                ('features_required', models.TextField(blank=True)),
                ('admin_panel_required', models.BooleanField(default=False)),
                ('payment_gateway_required', models.BooleanField(default=False)),
                ('maintenance_required', models.BooleanField(default=False)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto-updated from quoted amount, advance, and saved payments.', max_digits=10)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Advance Paid', 'Advance Paid'), ('Partially Paid', 'Partially Paid'), ('Fully Paid', 'Fully Paid'), ('Refunded', 'Refunded')], default='Not Paid', max_length=30)),
                ('project_status', models.CharField(choices=[('Lead', 'Lead'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Proposal Sent', 'Proposal Sent'), ('Client Finalised', 'Client Finalised'), ('Advance Paid', 'Advance Paid'), ('Content Pending', 'Content Pending'), ('In Development', 'In Development'), ('Review', 'Review'), ('Revision', 'Revision'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Maintenance', 'Maintenance'), ('Cancelled', 'Cancelled')], default='Lead', max_length=40)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('revision_rounds_included', models.PositiveIntegerField(default=1)),
                ('client_approval_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgressTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tasks', to='core.clientproject')),
            ],
            options={
                'ordering': ['order', 'task_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('Advance', 'Advance'), ('Partial', 'Partial'), ('Final', 'Final'), ('Maintenance', 'Maintenance'), ('Refund', 'Refund'), ('Other', 'Other')], default='Partial', max_length=30)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Razorpay', 'Razorpay'), ('Other', 'Other')], default='UPI', max_length=30)),
                ('payment_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.clientproject')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.clientproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDomainHosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_required', models.BooleanField(default=False)),
                ('domain_name', models.CharField(blank=True, max_length=180)),
                ('domain_provider', models.CharField(blank=True, max_length=140)),
                ('domain_expiry_date', models.DateField(blank=True, null=True)),
                ('hosting_required', models.BooleanField(default=False)),
                ('hosting_provider', models.CharField(blank=True, max_length=140)),
                ('hosting_plan', models.CharField(blank=True, max_length=140)),
                ('hosting_renewal_date', models.DateField(blank=True, null=True)),
                ('deployment_url', models.URLField(blank=True)),
                ('live_website_url', models.URLField(blank=True)),
                ('access_given_by_client', models.BooleanField(default=False)),
                ('stored_in_password_manager', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Do not store passwords here. Note only where access is safely stored.')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_hosting', to='core.clientproject')),
            ],
        ),
        migrations.CreateModel(
            name='ClientContentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_received', models.BooleanField(default=False)),
                ('photos_received', models.BooleanField(default=False)),
                ('service_details_received', models.BooleanField(default=False)),
                ('price_list_received', models.BooleanField(default=False)),
                ('about_content_received', models.BooleanField(default=False)),
                ('contact_details_received', models.BooleanField(default=False)),
                ('social_links_received', models.BooleanField(default=False)),
                ('testimonials_received', models.BooleanField(default=False)),
                ('gallery_images_received', models.BooleanField(default=False)),
                ('domain_access_received', models.BooleanField(default=False)),
                ('hosting_access_received', models.BooleanField(default=False)),
                ('content_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_status', to='core.clientproject')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.servicecategory'),
        ),
        migrations.RunPython(create_default_service_categories, remove_default_service_categories),
    ]
