# Generated by Django 4.2.30 on 2026-07-17 08:28

from django.db import migrations, models


def approve_existing_reviews(apps, schema_editor):
    Review = apps.get_model("core", "Review")
    Review.objects.update(status="Approved")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_client_clientproject_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='review',
            name='service_received',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('Website', 'Website feedback form'), ('Google', 'Google'), ('WhatsApp', 'WhatsApp'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Other', 'Other')], default='Website', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='submitted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.RunPython(approve_existing_reviews, migrations.RunPython.noop),
    ]
