# Generated by Django 4.2.30 on 2026-07-17 09:02

from django.db import migrations, models


def classify_public_pricing(apps, schema_editor):
    Package = apps.get_model("core", "Package")
    for package in Package.objects.all():
        name = package.title.lower()
        if "system" in name:
            pricing_type = "SCOPE_BASED"
        elif "premium" in name or "advanced" in name:
            pricing_type = "TAILORED"
        elif "starter" in name or name.startswith("basic"):
            pricing_type = "STARTING_ON_REQUEST"
        else:
            pricing_type = "CUSTOM_QUOTE"
        package.public_pricing_type = pricing_type
        package.save(update_fields=["public_pricing_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_review_email_review_location_review_service_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='budget_level',
            field=models.CharField(blank=True, choices=[('Entry-level project', 'Entry-level project'), ('Standard business project', 'Standard business project'), ('Premium business project', 'Premium business project'), ('Advanced/custom system', 'Advanced/custom system'), ('Not sure yet', 'Not sure yet')], max_length=40),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='estimated_pages',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='preferred_currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR — Indian Rupee'), ('USD', 'USD — US Dollar'), ('GBP', 'GBP — British Pound'), ('AUD', 'AUD — Australian Dollar'), ('CAD', 'CAD — Canadian Dollar'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='preferred_timeline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='required_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='public_pricing_type',
            field=models.CharField(choices=[('CUSTOM_QUOTE', 'Custom Quote'), ('TAILORED', 'Tailored Pricing'), ('SCOPE_BASED', 'Scope-Based Pricing'), ('STARTING_ON_REQUEST', 'Starting price available on request')], default='CUSTOM_QUOTE', help_text='Public label only. Internal INR pricing remains in the Price field.', max_length=30),
        ),
        migrations.RunPython(classify_public_pricing, migrations.RunPython.noop),
    ]
