# Generated by Django 4.2.30 on 2026-07-17 09:30

from django.db import migrations, models
import django.db.models.deletion


def seed_market_prices(apps, schema_editor):
    from core.pricing import MARKETS, PRICE_BANDS, price_band_key
    Package = apps.get_model("core", "Package")
    PackageMarketPrice = apps.get_model("core", "PackageMarketPrice")
    for package in Package.objects.all():
        band = PRICE_BANDS[price_band_key(package)]
        for market_code, (minimum, maximum) in band.items():
            currency_code, currency_symbol, display_order = MARKETS[market_code]
            PackageMarketPrice.objects.get_or_create(
                package=package,
                market_code=market_code,
                defaults={
                    "currency_code": currency_code,
                    "currency_symbol": currency_symbol,
                    "min_price": minimum,
                    "max_price": maximum,
                    "pricing_mode": "STARTING_FROM" if maximum is None else "RANGE",
                    "is_active": True,
                    "display_order": display_order,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_enquiry_budget_level_enquiry_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='displayed_price_context',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='final_quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='final_quote_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='selected_market',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='budget_level',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='PackageMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_code', models.CharField(choices=[('IN', 'India — INR'), ('US_INTL', 'United States / International — USD'), ('UK', 'United Kingdom — GBP'), ('AU', 'Australia — AUD'), ('CA', 'Canada — CAD')], max_length=12)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_symbol', models.CharField(max_length=4)),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('max_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('pricing_mode', models.CharField(choices=[('RANGE', 'Price range'), ('STARTING_FROM', 'Starting from')], default='RANGE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='core.package')),
            ],
            options={
                'ordering': ['display_order', 'market_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='packagemarketprice',
            constraint=models.UniqueConstraint(fields=('package', 'market_code'), name='unique_package_market_price'),
        ),
        migrations.RunPython(seed_market_prices, migrations.RunPython.noop),
    ]
