SERVICES = [
    ("Business Websites", "Professional websites for cafes, restaurants, travel agencies, gyms, shops, institutes, salons, and local service businesses.", "01"),
    ("Trips & Tours Websites", "Tour package websites with itinerary sections, destination pages, enquiry forms, WhatsApp CTA, and booking lead flow.", "02"),
    ("Restaurant/Cafe Websites", "Premium, mobile-friendly restaurant websites with menu, gallery, location, and WhatsApp flow.", "03"),
    ("Digital Menu / QR Menu Websites", "Fast-loading digital menus that customers can open from a QR code and use easily on phones.", "04"),
    ("Real Estate / Property Websites", "Premium property advisor websites with listings, locations, trust sections, consultation flow, and enquiry forms.", "05"),
    ("Salon & Makeup Artist Websites", "Professional websites for salons, beauty studios, bridal makeup artists, and personal beauty brands.", "06"),
    ("Pet Shop Websites", "Professional websites for pet shops, pet supply stores, grooming services, and pet care brands.", "07"),
    ("Hotel Websites", "Professional websites for hotels, guest houses, lodges, boutique stays, banquet hotels, and resorts.", "08"),
    ("Wedding & Event Planner Websites", "Premium websites for wedding planners, event planners, decorators, party organizers, and event management brands.", "09"),
    ("Web Design / Agency Websites", "Modern agency-style websites with services, process, portfolio preview, packages, trust sections, and quote CTA.", "10"),
    ("Landing Pages", "Focused single-page websites for offers, launches, services, and lead generation.", "11"),
    ("Portfolio Websites", "Personal brand websites for creators, professionals, coaches, and freelancers.", "12"),
    ("Small Business Websites", "Clean websites for service providers, clinics, consultants, repair services, tutors, and local professionals.", "13"),
    ("Website Redesign / Improvement", "Improve layout, mobile experience, clarity, speed, and conversion flow.", "14"),
    ("Responsive Website Development", "Websites built to work smoothly across desktop, tablet, and mobile screens.", "15"),
    ("Basic SEO-Friendly Website Setup", "Clean page structure, titles, descriptions, alt text, and search-friendly basics.", "16"),
    ("Domain/Hosting Setup Support", "Guidance for connecting domain, hosting, SSL, and launch setup.", "17"),
]

PACKAGES = [
    {
        "category": "Starter Business Website",
        "title": "Starter Business Website",
        "price": "₹12,000-₹18,000",
        "short_description": "A clean 3-5 section website for any small business that needs a professional online presence.",
        "included_features": ["Professional homepage", "About/business intro section", "Services or products section", "Gallery or highlights section", "Contact section", "WhatsApp button", "Call button", "Google Map embed", "Mobile responsive design", "Basic SEO title/description", "1-2 rounds minor revisions"],
        "scope_limits": ["Up to 5 sections", "Best for simple businesses", "Content and photos provided by client", "1-2 rounds minor revisions"],
        "is_featured": True,
    },
    {
        "category": "Professional Business Website",
        "title": "Professional Business Website",
        "price": "₹25,000-₹45,000",
        "short_description": "A stronger multi-page website for service providers, shops, gyms, institutes, clinics, salons, and personal brands.",
        "included_features": ["Premium homepage", "About page", "Services/products pages", "Portfolio/work or gallery page", "Testimonials section", "FAQ section", "Contact/enquiry form", "WhatsApp/call CTA", "Google Map", "Basic SEO-friendly structure", "Admin-saved enquiries", "2-3 rounds revisions"],
        "scope_limits": ["Up to 6-8 pages/sections", "Advanced features quoted separately", "2-3 rounds revisions"],
        "is_featured": True,
    },
    {
        "category": "Trips & Tours Website",
        "title": "Tour & Travel Website",
        "price": "₹30,000-₹60,000",
        "short_description": "A tour business website for destinations, trip packages, itinerary details, and booking enquiries.",
        "included_features": ["Premium travel homepage", "Tour package listing", "Individual package/detail sections", "Itinerary highlights", "Destination gallery", "Pricing or starting-from prices", "Booking/enquiry form", "WhatsApp CTA", "Google Map/location support", "FAQ section", "Basic SEO-friendly structure", "Admin-saved enquiries"],
        "scope_limits": ["Up to 8-10 tour packages", "Online payment/booking automation quoted separately", "Photos and package details provided by client"],
        "is_featured": True,
    },
    {
        "category": "Premium Business Website",
        "title": "Premium Business Website",
        "price": "₹50,000-₹75,000",
        "short_description": "A premium business website for brands that want stronger design, more trust sections, and a polished enquiry journey.",
        "included_features": ["Custom premium homepage", "Up to 8-10 pages/sections", "Service/product pages", "Portfolio or gallery section", "Testimonials/reviews section", "FAQ section", "Lead enquiry form", "WhatsApp/call CTA", "Google Map/location section", "Basic animations", "Basic SEO-friendly structure", "Speed/basic performance optimization", "Domain/hosting setup support", "Launch/setup support", "3 rounds revisions"],
        "scope_limits": ["Up to 8-10 pages/sections", "Advanced backend features quoted separately", "Content and photos finalized before development", "3 rounds revisions"],
        "is_featured": True,
    },
    {
        "category": "Premium Business Website",
        "title": "Premium Plus Business Website",
        "price": "₹75,000-₹1,20,000+",
        "short_description": "A high-end business website with deeper custom design, richer sections, stronger conversion flow, and advanced polish.",
        "included_features": ["Everything in Premium Business Website", "More custom page layouts", "More premium animations", "Advanced CTA flow", "Larger portfolio/gallery/product showcase", "Multiple landing pages or service pages", "Blog/news/offers setup placeholder", "Better performance optimization", "Content arrangement help", "More design polish", "More revision support", "Future admin/payment integration planning"],
        "scope_limits": ["Final quote depends on pages, content, integrations, and design level", "Custom backend/payment gateway quoted separately", "Timeline confirmed after full scope discussion"],
        "is_featured": True,
    },
    {
        "category": "Advanced Business System",
        "title": "Custom Business System",
        "price": "₹80,000+",
        "short_description": "A custom website system with admin panel, bookings, payments, dashboards, or content management.",
        "included_features": ["Custom backend", "Admin panel", "Enquiry/customer management", "Booking or request flow", "Payment gateway integration placeholder", "Content management", "Custom pages/modules", "Performance and launch setup support"],
        "scope_limits": ["Custom quote required", "Gateway keys and provider accounts are added only during real integration", "Domain and hosting charges are separate"],
        "is_featured": True,
    },
    {
        "category": "Digital Menu / Single Page Website",
        "title": "Starter Digital Menu",
        "price": "₹10,000",
        "short_description": "A clean single-page digital menu for smaller restaurants and cafes.",
        "included_features": ["1 single page website", "Up to 5 menu categories", "Up to 40 menu items", "Basic item names + prices", "Opening hours", "Google Map location", "Call button", "WhatsApp button", "Mobile-friendly design", "Basic clean layout", "1 round minor revision"],
        "scope_limits": ["Single page only", "Up to 40 menu items", "1 round minor revision"],
    },
    {
        "category": "Digital Menu / Single Page Website",
        "title": "Standard Digital Menu",
        "price": "₹12,000",
        "short_description": "A stronger digital menu with more items, photos, and section polish.",
        "included_features": ["Everything in Starter Digital Menu", "Up to 8 menu categories", "Up to 70 menu items", "Better section design", "Up to 10 food/photos setup", "Slightly better mobile layout", "2 rounds minor revisions"],
        "scope_limits": ["Single page digital menu", "Up to 70 menu items", "2 rounds minor revisions"],
    },
    {
        "category": "Digital Menu / Single Page Website",
        "title": "Advanced Digital Menu / Landing Page",
        "price": "₹16,000",
        "short_description": "A premium digital menu landing page with hero, offers, gallery, and stronger CTA flow.",
        "included_features": ["Everything in Standard Digital Menu", "Up to 100 menu items", "Hero section", "Offers/specials section", "Gallery section", "Better premium layout", "Basic SEO title/description", "Strong WhatsApp/call CTA", "Google Map section", "2-3 rounds revisions"],
        "scope_limits": ["Up to 100 menu items", "Extra charges apply above 100 items", "2-3 rounds revisions"],
        "is_featured": True,
    },
    {
        "category": "Basic Restaurant Website",
        "title": "Basic Website",
        "price": "₹18,000",
        "short_description": "A compact restaurant website covering the core pages customers expect.",
        "included_features": ["Home", "Menu", "Gallery", "About", "Location/Contact", "WhatsApp/call button", "Google Map", "Mobile responsive design", "Basic SEO-friendly structure", "Up to 5 pages/sections", "Up to 60 menu items", "Up to 15 photos", "2 rounds minor revisions"],
        "scope_limits": ["Up to 5 pages/sections", "Up to 60 menu items", "Up to 15 photos", "2 rounds minor revisions"],
    },
    {
        "category": "Basic Restaurant Website",
        "title": "Basic Plus",
        "price": "₹22,000-₹25,000",
        "short_description": "A more polished restaurant website with better gallery, offers, and content arrangement.",
        "included_features": ["Everything in Basic Website", "Up to 80-100 menu items", "More polished layout", "Better gallery setup", "Offers/highlights section", "More content arrangement", "Better mobile spacing", "2-3 rounds revisions"],
        "scope_limits": ["Up to 80-100 menu items", "2-3 rounds revisions", "Final quote depends on content and design level"],
    },
    {
        "category": "Professional Restaurant Website",
        "title": "Professional Website",
        "price": "₹30,000",
        "short_description": "A premium-looking restaurant website with stronger pages, enquiry flow, and mobile experience.",
        "included_features": ["Premium-looking homepage", "Full menu sections", "Gallery", "Offers/Specials section", "About section", "Location + Google Map", "Contact/enquiry flow", "WhatsApp/call button", "Better mobile experience", "Basic SEO-friendly structure", "Up to 6-7 pages/sections", "Up to 100 menu items", "Up to 25 photos", "3 rounds revisions"],
        "scope_limits": ["Up to 6-7 pages/sections", "Up to 100 menu items", "Up to 25 photos", "3 rounds revisions"],
        "is_featured": True,
    },
    {
        "category": "Professional Restaurant Website",
        "title": "Professional Plus",
        "price": "₹35,000-₹45,000",
        "short_description": "A more custom professional website with animations, richer sections, and speed basics.",
        "included_features": ["Everything in Professional Website", "More custom design", "More sections/pages", "Larger gallery", "More detailed menu layout", "Basic animations", "Better CTA flow", "Content arrangement help", "Speed/basic performance optimization"],
        "scope_limits": ["Final scope depends on custom sections", "Content and gallery size confirmed before quote"],
    },
    {
        "category": "Premium Restaurant Website",
        "title": "Premium Website",
        "price": "₹50,000",
        "short_description": "A custom premium restaurant website experience with strong brand story, reservation flow, and launch support.",
        "included_features": ["Custom premium design", "Full restaurant website experience", "Home page with strong hero section", "Advanced menu layout", "Gallery", "Offers/Specials section", "About/brand story section", "Location section with Google Map", "Contact section", "Reservation/enquiry form", "WhatsApp/call CTA", "Strong call-to-action flow", "Better mobile user experience", "Speed optimization", "Basic SEO-friendly structure", "Domain/hosting setup support", "Launch/setup support", "Up to 8 pages/sections", "Up to 120 menu items", "Up to 35 photos", "3 rounds revisions"],
        "scope_limits": ["Up to 8 pages/sections", "Up to 120 menu items", "Up to 35 photos", "3 rounds revisions"],
    },
    {
        "category": "Premium Restaurant Website",
        "title": "Premium Plus",
        "price": "₹60,000-₹75,000",
        "short_description": "An elevated custom build with richer animations, events/offers, testimonials, and deeper polish.",
        "included_features": ["Everything in Premium Website", "More custom sections", "More premium animations", "Larger menu", "Larger gallery", "More detailed reservation/enquiry flow", "Testimonials/reviews section", "Events/offers page", "Better performance optimization", "More design polish", "More revision support"],
        "scope_limits": ["Final quote depends on pages, menu size, photos, design level, content, and extra features"],
    },
    {
        "category": "Advanced Restaurant System",
        "title": "Advanced Restaurant System",
        "price": "₹80,000+",
        "short_description": "A custom restaurant system for teams that need admin controls, ordering, bookings, payments, or content management.",
        "included_features": ["Admin panel", "Menu update system", "Multi-branch pages", "Online table booking system", "Online ordering flow", "Payment integration", "Customer enquiry management", "Blog/news/offers management", "Custom backend"],
        "scope_limits": ["Custom quote required", "Domain and hosting charges are separate if required", "Payment gateway keys and provider setup are added only during real integration"],
        "is_featured": True,
    },
    {
        "category": "Salon & Makeup Artist Websites",
        "title": "Basic Salon Website",
        "price": "₹15,000+",
        "short_description": "A clean starter website for salons that need services, location, timings, gallery, and direct booking CTAs.",
        "included_features": ["Home page", "About salon", "Services list", "Basic price/menu section", "Gallery", "Timings", "Google Map", "Call button", "WhatsApp booking button", "Instagram link", "Mobile responsive design", "Basic SEO-friendly setup"],
        "scope_limits": [],
    },
    {
        "category": "Salon & Makeup Artist Websites",
        "title": "Professional Salon Website",
        "price": "₹25,000+",
        "short_description": "A polished salon website with categorized services, offers, proof sections, and a stronger booking enquiry flow.",
        "included_features": ["Home page", "About section", "Services with categories", "Hair, Skin, Makeup, and Nails sections", "Price list", "Gallery", "Before/after section", "Testimonials", "Offers section", "WhatsApp booking flow", "Contact form", "Google Map", "Instagram link", "Mobile responsive design", "Basic SEO", "Basic speed optimization", "Launch/setup support"],
        "scope_limits": [],
        "is_featured": True,
    },
    {
        "category": "Salon & Makeup Artist Websites",
        "title": "Premium Salon Website",
        "price": "₹40,000+",
        "short_description": "A premium salon website with custom design, detailed service pages, portfolio sections, and basic admin control.",
        "included_features": ["Premium custom design", "Service category pages", "Detailed service pages", "Staff/artist section", "Packages/offers section", "Advanced gallery", "Before/after portfolio", "Testimonials/reviews", "Booking enquiry form", "WhatsApp and call CTA flow", "Google Map", "Basic admin panel for services, offers, and gallery", "Mobile responsive design", "Basic SEO", "Speed optimization", "Launch/setup support"],
        "scope_limits": [],
    },
    {
        "category": "Salon & Makeup Artist Websites",
        "title": "Basic Makeup Artist Portfolio",
        "price": "₹12,000+",
        "short_description": "A simple beauty portfolio for makeup artists who need a professional gallery and fast WhatsApp booking path.",
        "included_features": ["Home page", "About artist", "Services", "Basic packages section", "Portfolio/gallery", "Instagram link", "WhatsApp booking button", "Call button", "Location/service area", "Mobile responsive design", "Basic SEO-friendly setup"],
        "scope_limits": [],
    },
    {
        "category": "Salon & Makeup Artist Websites",
        "title": "Professional Makeup Artist Website",
        "price": "₹22,000+",
        "short_description": "A complete makeup artist website for bridal, party, engagement, reception, and HD makeup enquiries.",
        "included_features": ["Home page", "About artist", "Bridal makeup section", "Party makeup section", "Engagement, reception, and HD makeup sections", "Packages/pricing section", "Portfolio gallery", "Client testimonials", "Booking enquiry form", "WhatsApp booking flow", "Instagram link", "Google Map/service area", "Mobile responsive design", "Basic SEO", "Launch/setup support"],
        "scope_limits": [],
        "is_featured": True,
    },
    {
        "category": "Salon & Makeup Artist Websites",
        "title": "Premium Makeup Artist Website",
        "price": "₹35,000+",
        "short_description": "A premium makeup artist website with detailed services, bridal/event packages, portfolio proof, FAQ, and basic admin control.",
        "included_features": ["Premium custom design", "Detailed service pages", "Bridal packages", "Party/event makeup packages", "Portfolio gallery", "Before/after section", "Testimonials", "FAQ section", "Booking enquiry form", "WhatsApp CTA flow", "Instagram/profile links", "Basic admin panel for gallery, packages, and testimonials", "Mobile responsive design", "Basic SEO", "Speed optimization", "Launch/setup support"],
        "scope_limits": [],
    },
    {
        "category": "Pet Shop Websites",
        "title": "Basic Pet Shop Website",
        "price": "₹16,000+",
        "short_description": "A clean starter website for pet shops that need essential business details, limited product highlights, contact CTAs, and local trust.",
        "included_features": ["Home page", "About pet shop", "Product categories overview", "Basic product highlights up to 6-8 items", "Simple grooming/service section if content is provided", "Simple offers/banner section", "Gallery up to 8-10 images", "Timings", "Google Map", "Call button", "WhatsApp enquiry button", "Instagram link", "Mobile responsive design", "Basic SEO-friendly setup"],
        "scope_limits": ["Best for simple pet shops and local pet supply stores", "Product photos and content provided by client", "Limited product highlights only, not full inventory", "No ecommerce, payment gateway, cart, or inventory system included"],
    },
    {
        "category": "Pet Shop Websites",
        "title": "Professional Pet Shop Website",
        "price": "₹28,000+",
        "short_description": "A stronger pet shop website for growing stores that need product/service sections, grooming enquiries, offers, testimonials, and a better lead flow.",
        "included_features": ["Home page", "About section", "Up to 4-5 product/service categories", "Pet food, toys, accessories, and grooming sections", "Featured products section up to 10-15 items", "Offers section", "Gallery up to 15 images", "Testimonials", "WhatsApp enquiry flow", "Contact form", "Google Map", "Instagram link", "Mobile responsive design", "Basic SEO", "Basic speed optimization", "Launch/setup support"],
        "scope_limits": ["Best for growing stores with multiple product/service categories", "Product photos and content provided by client", "Detailed inventory/ecommerce system quoted separately", "Online payment, cart, and stock management not included", "Includes 1-2 rounds of minor revisions"],
        "is_featured": True,
    },
    {
        "category": "Pet Shop Websites",
        "title": "Premium Pet Shop Website",
        "price": "₹45,000+",
        "short_description": "A premium pet shop website with custom design, detailed product/service pages, stronger trust sections, and basic admin control for limited updates.",
        "included_features": ["Premium custom design", "Product category pages", "Detailed product/service pages", "Grooming appointment enquiry", "Pet care information sections", "Packages/offers section", "Advanced gallery", "Testimonials/reviews", "FAQ section", "WhatsApp and call CTA flow", "Google Map", "Basic admin panel for limited products, offers, and gallery updates", "Mobile responsive design", "Basic SEO", "Speed optimization", "Launch/setup support"],
        "scope_limits": ["Final scope depends on products, services, gallery size, and admin panel needs", "Basic admin panel is for limited product/offer/gallery updates only", "Full ecommerce, online payment, cart, stock management, and advanced inventory system are not included", "Ecommerce/payment/inventory system will be quoted separately", "Includes 1-2 rounds of minor revisions"],
    },
    {
        "category": "Hotel Websites",
        "title": "Basic Hotel Website",
        "price": "₹18,000+",
        "short_description": "A clean starter website for small hotels, guest houses, lodges, and budget stays that need essential details and booking enquiries.",
        "included_features": ["Home page", "About hotel", "Rooms overview", "Basic amenities section", "Gallery up to 8-10 images", "Timings / check-in / check-out info", "Google Map", "Call button", "WhatsApp booking enquiry button", "Contact section", "Instagram/social link", "Mobile responsive design", "Basic SEO-friendly setup"],
        "scope_limits": ["Best for: Small hotels, guest houses, lodges, and budget stays.", "Best for hotels that need a simple online presence.", "No online booking system, payment gateway, real-time room availability, or admin panel included."],
    },
    {
        "category": "Hotel Websites",
        "title": "Professional Hotel Website",
        "price": "₹32,000+",
        "short_description": "A stronger hotel website for better room presentation, guest trust, location clarity, and booking enquiries.",
        "included_features": ["Home page", "About section", "Room categories section", "Room detail sections", "Amenities section", "Dining / restaurant section if available", "Banquet / conference section if available", "Gallery up to 15 images", "Testimonials/reviews section", "Nearby places section", "WhatsApp booking enquiry flow", "Contact form", "Google Map", "Call button", "Instagram/social link", "Mobile responsive design", "Basic SEO", "Basic speed optimization", "Launch/setup support"],
        "scope_limits": ["Best for: Hotels that want better room presentation, stronger trust, and clear booking enquiries.", "Best for hotels that want guests to check rooms, amenities, location, and enquiry options clearly.", "Online payment, real-time booking engine, advanced booking management, and admin panel are not included."],
        "is_featured": True,
    },
    {
        "category": "Hotel Websites",
        "title": "Premium Hotel Website",
        "price": "₹55,000+",
        "short_description": "A premium hotel website with custom design, room pages, strong trust sections, enquiry flow, and limited admin control.",
        "included_features": ["Premium custom design", "Home page", "About hotel", "Room category pages", "Detailed room pages", "Amenities section", "Dining / restaurant page", "Banquet / conference page", "Gallery section", "Nearby attractions section", "Testimonials/reviews", "FAQ section", "Booking enquiry form", "WhatsApp and call CTA flow", "Google Map", "Basic admin panel for limited room, gallery, and offer updates", "Mobile responsive design", "Basic SEO", "Speed optimization", "Launch/setup support"],
        "scope_limits": ["Best for: Premium hotels, boutique hotels, banquet hotels, resorts, and hotel brands.", "Basic admin panel is for limited room, offer, and gallery updates only.", "Online booking engine, payment gateway, real-time room availability, advanced booking calendar, and hotel management system are not included.", "These advanced systems will be quoted separately if required."],
    },
    {
        "category": "Wedding & Event Planner Websites",
        "title": "Basic Wedding/Event Planner Website",
        "price": "₹18,000+",
        "short_description": "A clean starter website for small event planners, decorators, party planners, and wedding service providers.",
        "included_features": ["Home page", "About business", "Services overview", "Basic event categories section", "Portfolio/gallery up to 10 images", "Testimonials section", "Location/service area", "Call button", "WhatsApp enquiry button", "Contact section", "Instagram/social link", "Mobile responsive design", "Basic SEO-friendly setup"],
        "scope_limits": ["Timeline: 5-7 days", "Best for: Small event planners, decorators, birthday/party planners, and wedding service providers who need a simple online presence.", "Best for simple online presence and enquiry generation.", "Portfolio photos and content should be provided by client.", "No admin panel, payment system, or advanced booking system included."],
    },
    {
        "category": "Wedding & Event Planner Websites",
        "title": "Professional Wedding/Event Planner Website",
        "price": "₹32,000+",
        "short_description": "A stronger event planner website with portfolio, service sections, enquiry flow, and professional brand presentation.",
        "included_features": ["Home page", "About section", "Detailed services section", "Wedding planning section", "Birthday/party planning section", "Corporate/event planning section if available", "Decoration/theme section", "Portfolio/gallery up to 20 images", "Testimonials/reviews section", "Packages/plans section", "Enquiry/contact form", "WhatsApp enquiry flow", "Google Map/service area section", "Call button", "Instagram/social link", "Mobile responsive design", "Basic SEO", "Basic speed optimization", "Launch/setup support"],
        "scope_limits": ["Timeline: 8-12 days", "Best for: Wedding planners and event planners who want a stronger portfolio, service sections, enquiry flow, and professional brand presentation.", "Best for businesses that want clients to check services, past work, packages, and enquiry options clearly.", "Photos, videos, package details, and content should be provided by client.", "Admin panel, payment gateway, and advanced booking calendar are not included."],
        "is_featured": True,
    },
    {
        "category": "Wedding & Event Planner Websites",
        "title": "Premium Wedding/Event Planner Website",
        "price": "₹55,000+",
        "short_description": "A high-end event planner website with premium custom design, detailed pages, portfolio storytelling, and limited admin control.",
        "included_features": ["Premium custom design", "Home page", "About business/brand story", "Detailed service pages", "Wedding planning page", "Event management page", "Decoration/theme page", "Portfolio/event gallery section", "Case study style event sections", "Packages/plans section", "Testimonials/reviews", "FAQ section", "Enquiry form", "WhatsApp and call CTA flow", "Google Map/service area section", "Basic admin panel for limited portfolio, packages, and testimonial updates", "Mobile responsive design", "Basic SEO", "Speed optimization", "Launch/setup support"],
        "scope_limits": ["Timeline: 12-20 days", "Best for: Premium wedding planners, event management companies, decorators, luxury event brands, and agencies that need a high-end portfolio website.", "Basic admin panel is for limited portfolio, package, and testimonial updates only.", "Advanced booking calendar, CRM, online payment, vendor management, guest management, and automation systems are not included.", "These advanced systems will be quoted separately if required."],
    },
]

PORTFOLIO = [
    ("Restaurant Website Demo", "A polished restaurant concept with menu, gallery, location, and WhatsApp enquiry flow.", "Django, HTML, CSS, JavaScript"),
    ("Cafe Landing Page Demo", "A warm cafe landing page designed for offers, ambience, menu highlights, and visits.", "HTML, CSS, JavaScript"),
    ("Gym Website Demo", "A conversion-focused gym website with plans, trainer highlights, and mobile CTA.", "Django, CSS, JavaScript"),
    ("Personal Portfolio Website", "A clean personal brand portfolio with services, case studies, and enquiry flow.", "Django, HTML, CSS"),
    ("Cricket Intelligence Dashboard Demo", "A cricket intelligence project presented with dashboard-style content and structured insights.", "Python, Django, JavaScript"),
    ("Real Estate Property Demo", "A premium property advisor homepage with listings, location trust, consultation CTA, and enquiry flow.", "Django, HTML, CSS, JavaScript"),
    ("Trips & Tours Website Demo", "A travel website concept with package cards, itinerary sections, destination gallery, and booking enquiry flow.", "Django, HTML, CSS, JavaScript"),
    ("Local Service Business Demo", "A polished service-provider website with pricing, FAQs, testimonials, and contact flow.", "Django, HTML, CSS, JavaScript"),
    ("Shop Website Demo", "A local shop website concept with product highlights, offers, location, and WhatsApp lead flow.", "HTML, CSS, JavaScript"),
    ("Salon Makeup Artist Demo", "A premium beauty website concept with services, bridal packages, gallery, testimonials, and WhatsApp booking.", "HTML, CSS, JavaScript"),
    ("Pet Shop Website Demo", "A friendly pet shop website concept with product categories, grooming enquiries, offers, reviews, and WhatsApp lead flow.", "Django, HTML, CSS, JavaScript"),
    ("Hotel Website Demo", "A premium hotel website concept with room categories, amenities, gallery, nearby attractions, and booking enquiry flow.", "Django, HTML, CSS, JavaScript"),
    ("Wedding & Event Planner Website Demo", "A premium event planning website demo for weddings, parties, corporate events, decoration services, portfolio showcase, and booking enquiries.", "Event Planner Demo"),
    ("Web Design Agency Demo", "A modern agency-style homepage with services, process, portfolio preview, pricing, and project quote CTA.", "Django, HTML, CSS, JavaScript"),
]
