from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("services/", views.services, name="services"),
    path("demo/<int:service_id>/<slug:slug>/", views.service_demo, name="service_demo"),
    path("packages/", views.packages, name="packages"),
    path("portfolio/", views.portfolio, name="portfolio"),
    path("portfolio/demo/<int:project_id>/<slug:slug>/", views.portfolio_demo, name="portfolio_demo"),
    path("process/", views.process, name="process"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("faq/", views.faq, name="faq"),
    path("checkout/", views.checkout, name="checkout"),
    path("payment/pending/", views.payment_pending, name="payment_pending"),
    path("payment/success/", views.payment_success, name="payment_success"),
    path("payment/failed/", views.payment_failed, name="payment_failed"),
    path("payment/callback/", views.payment_callback, name="payment_callback"),
    path("staff-dashboard/", views.staff_dashboard, name="staff_dashboard"),
    path("staff-dashboard/services/", views.staff_services, name="staff_services"),
    path("staff-dashboard/services/<slug:slug>/", views.staff_service_clients, name="staff_service_clients"),
    path("staff-dashboard/clients/", views.staff_clients, name="staff_clients"),
    path("staff-dashboard/projects/", views.staff_projects, name="staff_projects"),
    path("staff-dashboard/payments/", views.staff_payments, name="staff_payments"),
    path("staff-dashboard/content-status/", views.staff_content_statuses, name="staff_content_statuses"),
    path("staff-dashboard/follow-ups/", views.staff_followups, name="staff_followups"),
    path("staff-dashboard/clients/add/", views.staff_client_form, name="staff_client_add"),
    path("staff-dashboard/clients/<int:client_id>/", views.staff_client_detail, name="staff_client_detail"),
    path("staff-dashboard/clients/<int:client_id>/edit/", views.staff_client_form, name="staff_client_edit"),
    path("staff-dashboard/clients/<int:client_id>/projects/add/", views.staff_project_form, name="staff_project_add"),
    path("staff-dashboard/clients/<int:client_id>/projects/<int:project_id>/edit/", views.staff_project_form, name="staff_project_edit"),
    path("staff-dashboard/projects/<int:project_id>/payments/add/", views.staff_payment_form, name="staff_payment_add"),
    path("staff-dashboard/projects/<int:project_id>/notes/add/", views.staff_note_form, name="staff_note_add"),
    path("staff-dashboard/projects/<int:project_id>/content/", views.staff_content_status_form, name="staff_content_status"),
    path("staff-dashboard/projects/<int:project_id>/domain-hosting/", views.staff_domain_hosting_form, name="staff_domain_hosting"),
    path("staff-dashboard/projects/<int:project_id>/tasks/add/", views.staff_task_form, name="staff_task_add"),
    path("staff-dashboard/projects/<int:project_id>/tasks/<int:task_id>/edit/", views.staff_task_form, name="staff_task_edit"),
]
